version: '2'
services:
  ecommercejhipsterv1-app:
    image: ecommercejhipsterv1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommercejhipsterv1-postgresql:5432/eCommerceJhipsterV1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ecommercejhipsterv1-postgresql:
    extends:
      file: postgresql.yml
      service: ecommercejhipsterv1-postgresql
